language: python
branches:
    only:
        - master
        - /^\d\.\d+$/

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: pypy
      env: TOXENV=pypy
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true


install:
    - pip install -U pip tox codecov

script: tox

after_success:
    - codecov
